import type { Candidate } from "@/types/candidate";

const now = new Date().toISOString();
const minsAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

export const mockCandidates: Candidate[] = [
  {
    id: "c_demo_1",
    status: "REF_CALL_PENDING",
    fullName: "Avery Chen",
    email: "avery.chen@example.com",
    roleApplied: "Volunteer Coach",
    createdAt: minsAgo(220),
    lastActivityAt: minsAgo(12),
    stage: "REFERRAL_OUTREACH",
    tasks: {
      intakeForm: "DONE",
      referralContacted: "DONE",
      referralResponses: "WAITING",
      backgroundCheck: "NOT_STARTED",
    },
    humanCheckNeeded: false,
    humanCheckReasons: [],
    activity: [
      { at: minsAgo(220), label: "Prospect added by employer" },
      { at: minsAgo(200), label: "Intake form received" },
      { at: minsAgo(30), label: "Reference call started" },
    ],
    messages: [{ at: minsAgo(210), channel: "email", subject: "Request: reference details", status: "sent" }],
  },
  {
    id: "c_demo_2",
    status: "REF_CALL_PENDING",
    fullName: "Maya Patel",
    email: "maya.patel@example.com",
    roleApplied: "Camp Volunteer",
    createdAt: minsAgo(510),
    lastActivityAt: minsAgo(3),
    stage: "DECISION",
    tasks: {
      intakeForm: "DONE",
      referralContacted: "DONE",
      referralResponses: "DONE",
      backgroundCheck: "DONE",
    },
    humanCheckNeeded: false,
    humanCheckReasons: [],
    referenceCall: {
      callId: "call_demo_ok",
      summary: "Reference confirmed reliability and good communication. No concerns raised.",
      transcript: "Reference: She's punctual and great with kids...\nAgent: Any concerns?\nReference: None.",
      recordingUrl: "",
      verdict: "PASS",
      endedAt: minsAgo(6),
    },
    activity: [
      { at: minsAgo(510), label: "Prospect added by employer" },
      { at: minsAgo(480), label: "Intake form received" },
      { at: minsAgo(40), label: "Reference response received (PASS)" },
      { at: minsAgo(10), label: "Background check complete" },
    ],
    messages: [{ at: minsAgo(500), channel: "email", subject: "Request: reference details", status: "sent" }],
  },
  {
    id: "c_demo_3",
    status: "REF_CALL_PENDING",
    fullName: "Jordan Smith",
    email: "jordan.smith@example.com",
    roleApplied: "Youth Mentor",
    createdAt: minsAgo(90),
    lastActivityAt: minsAgo(1),
    stage: "FLAGGED",
    tasks: {
      intakeForm: "DONE",
      referralContacted: "DONE",
      referralResponses: "FAILED",
      backgroundCheck: "NOT_STARTED",
    },
    humanCheckNeeded: true,
    humanCheckReasons: ["Negative reference"],
    referenceCall: {
      callId: "call_demo_bad",
      summary: "Reference raised concerns about reliability and professionalism.",
      transcript: "Reference: I would not recommend...\nAgent: Can you elaborate?\nReference: Missed shifts and poor attitude.",
      recordingUrl: "",
      verdict: "FAIL",
      endedAt: minsAgo(2),
    },
    activity: [
      { at: minsAgo(90), label: "Prospect added by employer" },
      { at: minsAgo(60), label: "Intake form received" },
      { at: minsAgo(8), label: "Reference response received (FAIL)" },
    ],
    messages: [{ at: minsAgo(80), channel: "email", subject: "Request: reference details", status: "sent" }],
  },
];
